<div>
    {{$flightDetails->flight_name}}
    {{$flightDetails->to}}
    {{$flightDetails->from}}
    {{$flightDetails->arival_time}}
    {{$flightDetails->depature_time}}
    {{$flightDetails->depature_date}}
    {{$flightDetails->seats}}
    {{$flightDetails->flight_name}}
</div>
